name: Checks for new releases and deploys master
on:
  schedule:
    - cron:  '55 * * * *'
  workflow_dispatch:

jobs:
  external-trigger:
    id: version_check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3
      
      - name: Version diff
        run: |
          chmod u+x ./scripts/isUpdated.sh
          ./scripts/isUpdated.sh
      - name: Trigger build check
        if: ${{ hashFiles('DOCKER_VERSION.txt') != '' }}
        run: |
          echo "Triggering because there is the new version $(cat DOCKER_VERSION.txt)"

      