name: Checks for new releases and deploys master
on:
  schedule:
    - cron:  '55 * * * *'
  workflow_dispatch:

jobs:
  external-trigger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3
      
      - name: Version diff
        run: |
          chmod u+x ./scripts/isUpdated.sh
          ./scripts/isUpdated.sh
      - name: Trigger build check
        if: ${{ hashFiles('DOCKER_VERSION.txt') != '' }}
        run: |
          version=$(cat DOCKER_VERSION.txt)
          echo "Triggering because there is the new version $version"
          curl -s --request POST \
            --url 'https://api.github.com/repos/afonsoc12/docker-cloudflared/actions/workflows/docker_build_master.yml/dispatches' \
            -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
            -d '{"ref": "main", "inputs": {"version": "$version"}}'

      