name: Checks for new releases and deploys master
on:
  schedule:
    - cron:  '55 * * * *'
  workflow_dispatch:

jobs:
  external-trigger-master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3
      - name: Version diff
        run: |
          chmod u+x ./scripts/isUpdated.sh
          ./scripts/isUpdated.sh
      - name: Trigger build check
        if: "(test -f DOCKER_VERSION.txt && echo DOCKER_VERSION.txt exists) || echo DOCKER_VERSION.txt does not exist, skipping step"
        run: |
          echo "Triggering because there is the new version $(cat DOCKER_VERSION.txt)"

      